services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data_kc_poc:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - keycloak_network
    ports:
      - 5432:5432

  keycloak:
   
    build:
      context: .
      dockerfile: Dockerfile
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_FEATURES: scripts 
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
    volumes:
      - ./themes:/opt/keycloak/themes
      

volumes:
  postgres_data_kc_poc:
    driver: local

networks:
  keycloak_network:
    driver: bridge
